### PR TITLE
unretweeting retweets

### PR DESCRIPTION
**Pull request by sweeeetch**
unretweeting retweets 
*this is not my code *

### CODE REVIEW

**Comment by sweeeetch** [comment]
credit to this helpful guy : https://gist.github.com/antlionguard/000e24bb039e8824fa5c58d6e324c78e?permalink_comment_id=4148639#gistcomment-4148639

**Comment by Lyfhael** [comment]
I'm not sure to follow, there's already an option to unretweet retweets

**Comment by sweeeetch** [comment]
> I'm not sure to follow, there's already an option to unretweet retweets

Oh sorry! , I haven't seen it and I apologise for the confusion (also am new in github!:)

**Comment by Lyfhael** [comment]
> > I'm not sure to follow, there's already an option to unretweet retweets
> 
> Oh sorry! , I haven't seen it and I apologise for the confusion (also am new in github!:)

No problem :)

**Pull request closed without merging**
